Python 2.6.5 (r265:79096, Mar 19 2010, 21:48:26) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

    ****************************************************************
    Personal firewall software may warn about the connection IDLE
    makes to its subprocess using this computer's internal loopback
    interface.  This connection is not visible on any external
    interface and no data is sent to or received from the Internet.
    ****************************************************************
    
IDLE 2.6.5      ==== No Subprocess ====
>>> 
>>> (load "file")
SyntaxError: invalid syntax
>>> import os
>>> load ("E:\DEVSSIMPY\PYTHONDEVS\pydevs\examples2\essaidico")
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    load ("E:\DEVSSIMPY\PYTHONDEVS\pydevs\examples2\essaidico")
NameError: name 'load' is not defined
>>> f = open("E:\DEVSSIMPY\PYTHONDEVS\pydevs\examples2\essaidico",'r')
>>> teta = pickle.load(f)
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    teta = pickle.load(f)
  File "C:\Python26\lib\pickle.py", line 1370, in load
    return Unpickler(file).load()
  File "C:\Python26\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python26\lib\pickle.py", line 1028, in load_dict
    k = self.marker()
  File "C:\Python26\lib\pickle.py", line 874, in marker
    while stack[k] is not mark: k = k-1
IndexError: list index out of range
>>> load(f)
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    load(f)
NameError: name 'load' is not defined
>>> dico1
Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    dico1
NameError: name 'dico1' is not defined
>>> import pickle
>>> t = pickle.load(f)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    t = pickle.load(f)
  File "C:\Python26\lib\pickle.py", line 1370, in load
    return Unpickler(file).load()
  File "C:\Python26\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python26\lib\pickle.py", line 1069, in load_inst
    klass = self.find_class(module, name)
  File "C:\Python26\lib\pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named co1 = { 'a': {'t1': 't2' , 't11': 't21'} , 'b': {'f1': 'f2'} }
>>> dico1 = { 'a': {'t1': 't2' , 't11': 't21'} , 'b': {'f1': 'f2'} }
>>> dico1
{'a': {'t11': 't21', 't1': 't2'}, 'b': {'f1': 'f2'}}
>>> import pickle
>>> f = open('E:\DEVSSIMPY\PYTHONDEVS\pydevs\examples2\dicovar', 'w')
>>> pickle.dump(dico1, f)
>>> dico2 = pickle.load(f)
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    dico2 = pickle.load(f)
  File "C:\Python26\lib\pickle.py", line 1370, in load
    return Unpickler(file).load()
  File "C:\Python26\lib\pickle.py", line 857, in load
    key = read(1)
IOError: File not open for reading
>>> f = open('E:\DEVSSIMPY\PYTHONDEVS\pydevs\examples2\dicovar', 'w')
>>> dico2 = pickle.load(f)
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    dico2 = pickle.load(f)
  File "C:\Python26\lib\pickle.py", line 1370, in load
    return Unpickler(file).load()
  File "C:\Python26\lib\pickle.py", line 857, in load
    key = read(1)
IOError: File not open for reading
>>> f = open('E:\DEVSSIMPY\PYTHONDEVS\pydevs\examples2\dicovar', 'r')
>>> dico2 = pickle.load(f)
>>> dico2
{'a': {'t11': 't21', 't1': 't2'}, 'b': {'f1': 'f2'}}
>>> 
